// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: zp_meta.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "zp_meta.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace ZPMeta {

namespace {

const ::google::protobuf::Descriptor* Node_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Node_reflection_ = NULL;
const ::google::protobuf::Descriptor* Partitions_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Partitions_reflection_ = NULL;
const ::google::protobuf::Descriptor* MetaCmd_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MetaCmd_reflection_ = NULL;
const ::google::protobuf::Descriptor* MetaCmd_Join_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MetaCmd_Join_reflection_ = NULL;
const ::google::protobuf::Descriptor* MetaCmd_Ping_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MetaCmd_Ping_reflection_ = NULL;
const ::google::protobuf::Descriptor* MetaCmd_Update_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MetaCmd_Update_reflection_ = NULL;
const ::google::protobuf::Descriptor* MetaCmd_Sync_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MetaCmd_Sync_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* MetaCmd_Type_descriptor_ = NULL;
const ::google::protobuf::Descriptor* MetaCmdResponse_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MetaCmdResponse_reflection_ = NULL;
const ::google::protobuf::Descriptor* MetaCmdResponse_Status_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MetaCmdResponse_Status_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* MetaCmdResponse_Type_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_zp_5fmeta_2eproto() {
  protobuf_AddDesc_zp_5fmeta_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "zp_meta.proto");
  GOOGLE_CHECK(file != NULL);
  Node_descriptor_ = file->message_type(0);
  static const int Node_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Node, ip_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Node, port_),
  };
  Node_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Node_descriptor_,
      Node::default_instance_,
      Node_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Node, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Node, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Node));
  Partitions_descriptor_ = file->message_type(1);
  static const int Partitions_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Partitions, id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Partitions, master_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Partitions, slaves_),
  };
  Partitions_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Partitions_descriptor_,
      Partitions::default_instance_,
      Partitions_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Partitions, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Partitions, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Partitions));
  MetaCmd_descriptor_ = file->message_type(2);
  static const int MetaCmd_offsets_[5] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MetaCmd, type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MetaCmd, join_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MetaCmd, ping_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MetaCmd, update_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MetaCmd, sync_),
  };
  MetaCmd_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      MetaCmd_descriptor_,
      MetaCmd::default_instance_,
      MetaCmd_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MetaCmd, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MetaCmd, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(MetaCmd));
  MetaCmd_Join_descriptor_ = MetaCmd_descriptor_->nested_type(0);
  static const int MetaCmd_Join_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MetaCmd_Join, node_),
  };
  MetaCmd_Join_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      MetaCmd_Join_descriptor_,
      MetaCmd_Join::default_instance_,
      MetaCmd_Join_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MetaCmd_Join, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MetaCmd_Join, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(MetaCmd_Join));
  MetaCmd_Ping_descriptor_ = MetaCmd_descriptor_->nested_type(1);
  static const int MetaCmd_Ping_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MetaCmd_Ping, node_),
  };
  MetaCmd_Ping_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      MetaCmd_Ping_descriptor_,
      MetaCmd_Ping::default_instance_,
      MetaCmd_Ping_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MetaCmd_Ping, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MetaCmd_Ping, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(MetaCmd_Ping));
  MetaCmd_Update_descriptor_ = MetaCmd_descriptor_->nested_type(2);
  static const int MetaCmd_Update_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MetaCmd_Update, info_),
  };
  MetaCmd_Update_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      MetaCmd_Update_descriptor_,
      MetaCmd_Update::default_instance_,
      MetaCmd_Update_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MetaCmd_Update, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MetaCmd_Update, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(MetaCmd_Update));
  MetaCmd_Sync_descriptor_ = MetaCmd_descriptor_->nested_type(3);
  static const int MetaCmd_Sync_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MetaCmd_Sync, node_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MetaCmd_Sync, filenum_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MetaCmd_Sync, offset_),
  };
  MetaCmd_Sync_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      MetaCmd_Sync_descriptor_,
      MetaCmd_Sync::default_instance_,
      MetaCmd_Sync_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MetaCmd_Sync, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MetaCmd_Sync, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(MetaCmd_Sync));
  MetaCmd_Type_descriptor_ = MetaCmd_descriptor_->enum_type(0);
  MetaCmdResponse_descriptor_ = file->message_type(3);
  static const int MetaCmdResponse_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MetaCmdResponse, type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MetaCmdResponse, status_),
  };
  MetaCmdResponse_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      MetaCmdResponse_descriptor_,
      MetaCmdResponse::default_instance_,
      MetaCmdResponse_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MetaCmdResponse, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MetaCmdResponse, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(MetaCmdResponse));
  MetaCmdResponse_Status_descriptor_ = MetaCmdResponse_descriptor_->nested_type(0);
  static const int MetaCmdResponse_Status_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MetaCmdResponse_Status, code_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MetaCmdResponse_Status, msg_),
  };
  MetaCmdResponse_Status_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      MetaCmdResponse_Status_descriptor_,
      MetaCmdResponse_Status::default_instance_,
      MetaCmdResponse_Status_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MetaCmdResponse_Status, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MetaCmdResponse_Status, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(MetaCmdResponse_Status));
  MetaCmdResponse_Type_descriptor_ = MetaCmdResponse_descriptor_->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_zp_5fmeta_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Node_descriptor_, &Node::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Partitions_descriptor_, &Partitions::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    MetaCmd_descriptor_, &MetaCmd::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    MetaCmd_Join_descriptor_, &MetaCmd_Join::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    MetaCmd_Ping_descriptor_, &MetaCmd_Ping::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    MetaCmd_Update_descriptor_, &MetaCmd_Update::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    MetaCmd_Sync_descriptor_, &MetaCmd_Sync::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    MetaCmdResponse_descriptor_, &MetaCmdResponse::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    MetaCmdResponse_Status_descriptor_, &MetaCmdResponse_Status::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_zp_5fmeta_2eproto() {
  delete Node::default_instance_;
  delete Node_reflection_;
  delete Partitions::default_instance_;
  delete Partitions_reflection_;
  delete MetaCmd::default_instance_;
  delete MetaCmd_reflection_;
  delete MetaCmd_Join::default_instance_;
  delete MetaCmd_Join_reflection_;
  delete MetaCmd_Ping::default_instance_;
  delete MetaCmd_Ping_reflection_;
  delete MetaCmd_Update::default_instance_;
  delete MetaCmd_Update_reflection_;
  delete MetaCmd_Sync::default_instance_;
  delete MetaCmd_Sync_reflection_;
  delete MetaCmdResponse::default_instance_;
  delete MetaCmdResponse_reflection_;
  delete MetaCmdResponse_Status::default_instance_;
  delete MetaCmdResponse_Status_reflection_;
}

void protobuf_AddDesc_zp_5fmeta_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\rzp_meta.proto\022\006ZPMeta\" \n\004Node\022\n\n\002ip\030\001 "
    "\002(\014\022\014\n\004port\030\002 \002(\005\"T\n\nPartitions\022\n\n\002id\030\001 "
    "\002(\005\022\034\n\006master\030\002 \002(\0132\014.ZPMeta.Node\022\034\n\006sla"
    "ves\030\003 \003(\0132\014.ZPMeta.Node\"\262\003\n\007MetaCmd\022\"\n\004t"
    "ype\030\001 \002(\0162\024.ZPMeta.MetaCmd.Type\022\"\n\004join\030"
    "\002 \001(\0132\024.ZPMeta.MetaCmd.Join\022\"\n\004ping\030\003 \001("
    "\0132\024.ZPMeta.MetaCmd.Ping\022&\n\006update\030\004 \001(\0132"
    "\026.ZPMeta.MetaCmd.Update\022\"\n\004sync\030\005 \001(\0132\024."
    "ZPMeta.MetaCmd.Sync\032\"\n\004Join\022\032\n\004node\030\001 \002("
    "\0132\014.ZPMeta.Node\032\"\n\004Ping\022\032\n\004node\030\001 \002(\0132\014."
    "ZPMeta.Node\032*\n\006Update\022 \n\004info\030\001 \003(\0132\022.ZP"
    "Meta.Partitions\032I\n\004Sync\022\032\n\004node\030\001 \002(\0132\014."
    "ZPMeta.Node\022\022\n\007filenum\030\002 \002(\005:\0010\022\021\n\006offse"
    "t\030\003 \002(\005:\0010\"0\n\004Type\022\010\n\004JOIN\020\001\022\010\n\004PING\020\002\022\n"
    "\n\006UPDATE\020\003\022\010\n\004SYNC\020\004\"\304\001\n\017MetaCmdResponse"
    "\022*\n\004type\030\001 \002(\0162\034.ZPMeta.MetaCmdResponse."
    "Type\022.\n\006status\030\002 \002(\0132\036.ZPMeta.MetaCmdRes"
    "ponse.Status\032#\n\006Status\022\014\n\004code\030\001 \002(\005\022\013\n\003"
    "msg\030\002 \001(\014\"0\n\004Type\022\010\n\004JOIN\020\001\022\010\n\004PING\020\002\022\n\n"
    "\006UPDATE\020\003\022\010\n\004SYNC\020\004", 779);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "zp_meta.proto", &protobuf_RegisterTypes);
  Node::default_instance_ = new Node();
  Partitions::default_instance_ = new Partitions();
  MetaCmd::default_instance_ = new MetaCmd();
  MetaCmd_Join::default_instance_ = new MetaCmd_Join();
  MetaCmd_Ping::default_instance_ = new MetaCmd_Ping();
  MetaCmd_Update::default_instance_ = new MetaCmd_Update();
  MetaCmd_Sync::default_instance_ = new MetaCmd_Sync();
  MetaCmdResponse::default_instance_ = new MetaCmdResponse();
  MetaCmdResponse_Status::default_instance_ = new MetaCmdResponse_Status();
  Node::default_instance_->InitAsDefaultInstance();
  Partitions::default_instance_->InitAsDefaultInstance();
  MetaCmd::default_instance_->InitAsDefaultInstance();
  MetaCmd_Join::default_instance_->InitAsDefaultInstance();
  MetaCmd_Ping::default_instance_->InitAsDefaultInstance();
  MetaCmd_Update::default_instance_->InitAsDefaultInstance();
  MetaCmd_Sync::default_instance_->InitAsDefaultInstance();
  MetaCmdResponse::default_instance_->InitAsDefaultInstance();
  MetaCmdResponse_Status::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_zp_5fmeta_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_zp_5fmeta_2eproto {
  StaticDescriptorInitializer_zp_5fmeta_2eproto() {
    protobuf_AddDesc_zp_5fmeta_2eproto();
  }
} static_descriptor_initializer_zp_5fmeta_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int Node::kIpFieldNumber;
const int Node::kPortFieldNumber;
#endif  // !_MSC_VER

Node::Node()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void Node::InitAsDefaultInstance() {
}

Node::Node(const Node& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void Node::SharedCtor() {
  _cached_size_ = 0;
  ip_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  port_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Node::~Node() {
  SharedDtor();
}

void Node::SharedDtor() {
  if (ip_ != &::google::protobuf::internal::kEmptyString) {
    delete ip_;
  }
  if (this != default_instance_) {
  }
}

void Node::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Node::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Node_descriptor_;
}

const Node& Node::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_zp_5fmeta_2eproto();
  return *default_instance_;
}

Node* Node::default_instance_ = NULL;

Node* Node::New() const {
  return new Node;
}

void Node::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_ip()) {
      if (ip_ != &::google::protobuf::internal::kEmptyString) {
        ip_->clear();
      }
    }
    port_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Node::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required bytes ip = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_ip()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_port;
        break;
      }

      // required int32 port = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_port:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &port_)));
          set_has_port();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void Node::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required bytes ip = 1;
  if (has_ip()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytes(
      1, this->ip(), output);
  }

  // required int32 port = 2;
  if (has_port()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->port(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* Node::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required bytes ip = 1;
  if (has_ip()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        1, this->ip(), target);
  }

  // required int32 port = 2;
  if (has_port()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->port(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int Node::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required bytes ip = 1;
    if (has_ip()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->ip());
    }

    // required int32 port = 2;
    if (has_port()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->port());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Node::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Node* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Node*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Node::MergeFrom(const Node& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_ip()) {
      set_ip(from.ip());
    }
    if (from.has_port()) {
      set_port(from.port());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Node::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Node::CopyFrom(const Node& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Node::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void Node::Swap(Node* other) {
  if (other != this) {
    std::swap(ip_, other->ip_);
    std::swap(port_, other->port_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Node::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Node_descriptor_;
  metadata.reflection = Node_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int Partitions::kIdFieldNumber;
const int Partitions::kMasterFieldNumber;
const int Partitions::kSlavesFieldNumber;
#endif  // !_MSC_VER

Partitions::Partitions()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void Partitions::InitAsDefaultInstance() {
  master_ = const_cast< ::ZPMeta::Node*>(&::ZPMeta::Node::default_instance());
}

Partitions::Partitions(const Partitions& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void Partitions::SharedCtor() {
  _cached_size_ = 0;
  id_ = 0;
  master_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Partitions::~Partitions() {
  SharedDtor();
}

void Partitions::SharedDtor() {
  if (this != default_instance_) {
    delete master_;
  }
}

void Partitions::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Partitions::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Partitions_descriptor_;
}

const Partitions& Partitions::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_zp_5fmeta_2eproto();
  return *default_instance_;
}

Partitions* Partitions::default_instance_ = NULL;

Partitions* Partitions::New() const {
  return new Partitions;
}

void Partitions::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    id_ = 0;
    if (has_master()) {
      if (master_ != NULL) master_->::ZPMeta::Node::Clear();
    }
  }
  slaves_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Partitions::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 id = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &id_)));
          set_has_id();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_master;
        break;
      }

      // required .ZPMeta.Node master = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_master:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_master()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_slaves;
        break;
      }

      // repeated .ZPMeta.Node slaves = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_slaves:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_slaves()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_slaves;
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void Partitions::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required int32 id = 1;
  if (has_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->id(), output);
  }

  // required .ZPMeta.Node master = 2;
  if (has_master()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->master(), output);
  }

  // repeated .ZPMeta.Node slaves = 3;
  for (int i = 0; i < this->slaves_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->slaves(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* Partitions::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required int32 id = 1;
  if (has_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->id(), target);
  }

  // required .ZPMeta.Node master = 2;
  if (has_master()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->master(), target);
  }

  // repeated .ZPMeta.Node slaves = 3;
  for (int i = 0; i < this->slaves_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        3, this->slaves(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int Partitions::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 id = 1;
    if (has_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->id());
    }

    // required .ZPMeta.Node master = 2;
    if (has_master()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->master());
    }

  }
  // repeated .ZPMeta.Node slaves = 3;
  total_size += 1 * this->slaves_size();
  for (int i = 0; i < this->slaves_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->slaves(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Partitions::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Partitions* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Partitions*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Partitions::MergeFrom(const Partitions& from) {
  GOOGLE_CHECK_NE(&from, this);
  slaves_.MergeFrom(from.slaves_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_id()) {
      set_id(from.id());
    }
    if (from.has_master()) {
      mutable_master()->::ZPMeta::Node::MergeFrom(from.master());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Partitions::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Partitions::CopyFrom(const Partitions& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Partitions::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  if (has_master()) {
    if (!this->master().IsInitialized()) return false;
  }
  for (int i = 0; i < slaves_size(); i++) {
    if (!this->slaves(i).IsInitialized()) return false;
  }
  return true;
}

void Partitions::Swap(Partitions* other) {
  if (other != this) {
    std::swap(id_, other->id_);
    std::swap(master_, other->master_);
    slaves_.Swap(&other->slaves_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Partitions::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Partitions_descriptor_;
  metadata.reflection = Partitions_reflection_;
  return metadata;
}


// ===================================================================

const ::google::protobuf::EnumDescriptor* MetaCmd_Type_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MetaCmd_Type_descriptor_;
}
bool MetaCmd_Type_IsValid(int value) {
  switch(value) {
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

#ifndef _MSC_VER
const MetaCmd_Type MetaCmd::JOIN;
const MetaCmd_Type MetaCmd::PING;
const MetaCmd_Type MetaCmd::UPDATE;
const MetaCmd_Type MetaCmd::SYNC;
const MetaCmd_Type MetaCmd::Type_MIN;
const MetaCmd_Type MetaCmd::Type_MAX;
const int MetaCmd::Type_ARRAYSIZE;
#endif  // _MSC_VER
#ifndef _MSC_VER
const int MetaCmd_Join::kNodeFieldNumber;
#endif  // !_MSC_VER

MetaCmd_Join::MetaCmd_Join()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void MetaCmd_Join::InitAsDefaultInstance() {
  node_ = const_cast< ::ZPMeta::Node*>(&::ZPMeta::Node::default_instance());
}

MetaCmd_Join::MetaCmd_Join(const MetaCmd_Join& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void MetaCmd_Join::SharedCtor() {
  _cached_size_ = 0;
  node_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MetaCmd_Join::~MetaCmd_Join() {
  SharedDtor();
}

void MetaCmd_Join::SharedDtor() {
  if (this != default_instance_) {
    delete node_;
  }
}

void MetaCmd_Join::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MetaCmd_Join::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MetaCmd_Join_descriptor_;
}

const MetaCmd_Join& MetaCmd_Join::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_zp_5fmeta_2eproto();
  return *default_instance_;
}

MetaCmd_Join* MetaCmd_Join::default_instance_ = NULL;

MetaCmd_Join* MetaCmd_Join::New() const {
  return new MetaCmd_Join;
}

void MetaCmd_Join::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_node()) {
      if (node_ != NULL) node_->::ZPMeta::Node::Clear();
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool MetaCmd_Join::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .ZPMeta.Node node = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_node()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void MetaCmd_Join::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required .ZPMeta.Node node = 1;
  if (has_node()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->node(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* MetaCmd_Join::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required .ZPMeta.Node node = 1;
  if (has_node()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->node(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int MetaCmd_Join::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required .ZPMeta.Node node = 1;
    if (has_node()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->node());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MetaCmd_Join::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const MetaCmd_Join* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const MetaCmd_Join*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void MetaCmd_Join::MergeFrom(const MetaCmd_Join& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_node()) {
      mutable_node()->::ZPMeta::Node::MergeFrom(from.node());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void MetaCmd_Join::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MetaCmd_Join::CopyFrom(const MetaCmd_Join& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MetaCmd_Join::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  if (has_node()) {
    if (!this->node().IsInitialized()) return false;
  }
  return true;
}

void MetaCmd_Join::Swap(MetaCmd_Join* other) {
  if (other != this) {
    std::swap(node_, other->node_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata MetaCmd_Join::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MetaCmd_Join_descriptor_;
  metadata.reflection = MetaCmd_Join_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int MetaCmd_Ping::kNodeFieldNumber;
#endif  // !_MSC_VER

MetaCmd_Ping::MetaCmd_Ping()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void MetaCmd_Ping::InitAsDefaultInstance() {
  node_ = const_cast< ::ZPMeta::Node*>(&::ZPMeta::Node::default_instance());
}

MetaCmd_Ping::MetaCmd_Ping(const MetaCmd_Ping& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void MetaCmd_Ping::SharedCtor() {
  _cached_size_ = 0;
  node_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MetaCmd_Ping::~MetaCmd_Ping() {
  SharedDtor();
}

void MetaCmd_Ping::SharedDtor() {
  if (this != default_instance_) {
    delete node_;
  }
}

void MetaCmd_Ping::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MetaCmd_Ping::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MetaCmd_Ping_descriptor_;
}

const MetaCmd_Ping& MetaCmd_Ping::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_zp_5fmeta_2eproto();
  return *default_instance_;
}

MetaCmd_Ping* MetaCmd_Ping::default_instance_ = NULL;

MetaCmd_Ping* MetaCmd_Ping::New() const {
  return new MetaCmd_Ping;
}

void MetaCmd_Ping::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_node()) {
      if (node_ != NULL) node_->::ZPMeta::Node::Clear();
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool MetaCmd_Ping::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .ZPMeta.Node node = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_node()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void MetaCmd_Ping::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required .ZPMeta.Node node = 1;
  if (has_node()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->node(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* MetaCmd_Ping::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required .ZPMeta.Node node = 1;
  if (has_node()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->node(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int MetaCmd_Ping::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required .ZPMeta.Node node = 1;
    if (has_node()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->node());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MetaCmd_Ping::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const MetaCmd_Ping* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const MetaCmd_Ping*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void MetaCmd_Ping::MergeFrom(const MetaCmd_Ping& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_node()) {
      mutable_node()->::ZPMeta::Node::MergeFrom(from.node());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void MetaCmd_Ping::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MetaCmd_Ping::CopyFrom(const MetaCmd_Ping& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MetaCmd_Ping::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  if (has_node()) {
    if (!this->node().IsInitialized()) return false;
  }
  return true;
}

void MetaCmd_Ping::Swap(MetaCmd_Ping* other) {
  if (other != this) {
    std::swap(node_, other->node_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata MetaCmd_Ping::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MetaCmd_Ping_descriptor_;
  metadata.reflection = MetaCmd_Ping_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int MetaCmd_Update::kInfoFieldNumber;
#endif  // !_MSC_VER

MetaCmd_Update::MetaCmd_Update()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void MetaCmd_Update::InitAsDefaultInstance() {
}

MetaCmd_Update::MetaCmd_Update(const MetaCmd_Update& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void MetaCmd_Update::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MetaCmd_Update::~MetaCmd_Update() {
  SharedDtor();
}

void MetaCmd_Update::SharedDtor() {
  if (this != default_instance_) {
  }
}

void MetaCmd_Update::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MetaCmd_Update::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MetaCmd_Update_descriptor_;
}

const MetaCmd_Update& MetaCmd_Update::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_zp_5fmeta_2eproto();
  return *default_instance_;
}

MetaCmd_Update* MetaCmd_Update::default_instance_ = NULL;

MetaCmd_Update* MetaCmd_Update::New() const {
  return new MetaCmd_Update;
}

void MetaCmd_Update::Clear() {
  info_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool MetaCmd_Update::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .ZPMeta.Partitions info = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_info:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_info()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(10)) goto parse_info;
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void MetaCmd_Update::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated .ZPMeta.Partitions info = 1;
  for (int i = 0; i < this->info_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->info(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* MetaCmd_Update::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // repeated .ZPMeta.Partitions info = 1;
  for (int i = 0; i < this->info_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->info(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int MetaCmd_Update::ByteSize() const {
  int total_size = 0;

  // repeated .ZPMeta.Partitions info = 1;
  total_size += 1 * this->info_size();
  for (int i = 0; i < this->info_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->info(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MetaCmd_Update::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const MetaCmd_Update* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const MetaCmd_Update*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void MetaCmd_Update::MergeFrom(const MetaCmd_Update& from) {
  GOOGLE_CHECK_NE(&from, this);
  info_.MergeFrom(from.info_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void MetaCmd_Update::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MetaCmd_Update::CopyFrom(const MetaCmd_Update& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MetaCmd_Update::IsInitialized() const {

  for (int i = 0; i < info_size(); i++) {
    if (!this->info(i).IsInitialized()) return false;
  }
  return true;
}

void MetaCmd_Update::Swap(MetaCmd_Update* other) {
  if (other != this) {
    info_.Swap(&other->info_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata MetaCmd_Update::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MetaCmd_Update_descriptor_;
  metadata.reflection = MetaCmd_Update_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int MetaCmd_Sync::kNodeFieldNumber;
const int MetaCmd_Sync::kFilenumFieldNumber;
const int MetaCmd_Sync::kOffsetFieldNumber;
#endif  // !_MSC_VER

MetaCmd_Sync::MetaCmd_Sync()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void MetaCmd_Sync::InitAsDefaultInstance() {
  node_ = const_cast< ::ZPMeta::Node*>(&::ZPMeta::Node::default_instance());
}

MetaCmd_Sync::MetaCmd_Sync(const MetaCmd_Sync& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void MetaCmd_Sync::SharedCtor() {
  _cached_size_ = 0;
  node_ = NULL;
  filenum_ = 0;
  offset_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MetaCmd_Sync::~MetaCmd_Sync() {
  SharedDtor();
}

void MetaCmd_Sync::SharedDtor() {
  if (this != default_instance_) {
    delete node_;
  }
}

void MetaCmd_Sync::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MetaCmd_Sync::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MetaCmd_Sync_descriptor_;
}

const MetaCmd_Sync& MetaCmd_Sync::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_zp_5fmeta_2eproto();
  return *default_instance_;
}

MetaCmd_Sync* MetaCmd_Sync::default_instance_ = NULL;

MetaCmd_Sync* MetaCmd_Sync::New() const {
  return new MetaCmd_Sync;
}

void MetaCmd_Sync::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_node()) {
      if (node_ != NULL) node_->::ZPMeta::Node::Clear();
    }
    filenum_ = 0;
    offset_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool MetaCmd_Sync::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .ZPMeta.Node node = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_node()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_filenum;
        break;
      }

      // required int32 filenum = 2 [default = 0];
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_filenum:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &filenum_)));
          set_has_filenum();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_offset;
        break;
      }

      // required int32 offset = 3 [default = 0];
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_offset:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &offset_)));
          set_has_offset();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void MetaCmd_Sync::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required .ZPMeta.Node node = 1;
  if (has_node()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->node(), output);
  }

  // required int32 filenum = 2 [default = 0];
  if (has_filenum()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->filenum(), output);
  }

  // required int32 offset = 3 [default = 0];
  if (has_offset()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->offset(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* MetaCmd_Sync::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required .ZPMeta.Node node = 1;
  if (has_node()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->node(), target);
  }

  // required int32 filenum = 2 [default = 0];
  if (has_filenum()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->filenum(), target);
  }

  // required int32 offset = 3 [default = 0];
  if (has_offset()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->offset(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int MetaCmd_Sync::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required .ZPMeta.Node node = 1;
    if (has_node()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->node());
    }

    // required int32 filenum = 2 [default = 0];
    if (has_filenum()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->filenum());
    }

    // required int32 offset = 3 [default = 0];
    if (has_offset()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->offset());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MetaCmd_Sync::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const MetaCmd_Sync* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const MetaCmd_Sync*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void MetaCmd_Sync::MergeFrom(const MetaCmd_Sync& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_node()) {
      mutable_node()->::ZPMeta::Node::MergeFrom(from.node());
    }
    if (from.has_filenum()) {
      set_filenum(from.filenum());
    }
    if (from.has_offset()) {
      set_offset(from.offset());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void MetaCmd_Sync::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MetaCmd_Sync::CopyFrom(const MetaCmd_Sync& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MetaCmd_Sync::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;

  if (has_node()) {
    if (!this->node().IsInitialized()) return false;
  }
  return true;
}

void MetaCmd_Sync::Swap(MetaCmd_Sync* other) {
  if (other != this) {
    std::swap(node_, other->node_);
    std::swap(filenum_, other->filenum_);
    std::swap(offset_, other->offset_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata MetaCmd_Sync::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MetaCmd_Sync_descriptor_;
  metadata.reflection = MetaCmd_Sync_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int MetaCmd::kTypeFieldNumber;
const int MetaCmd::kJoinFieldNumber;
const int MetaCmd::kPingFieldNumber;
const int MetaCmd::kUpdateFieldNumber;
const int MetaCmd::kSyncFieldNumber;
#endif  // !_MSC_VER

MetaCmd::MetaCmd()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void MetaCmd::InitAsDefaultInstance() {
  join_ = const_cast< ::ZPMeta::MetaCmd_Join*>(&::ZPMeta::MetaCmd_Join::default_instance());
  ping_ = const_cast< ::ZPMeta::MetaCmd_Ping*>(&::ZPMeta::MetaCmd_Ping::default_instance());
  update_ = const_cast< ::ZPMeta::MetaCmd_Update*>(&::ZPMeta::MetaCmd_Update::default_instance());
  sync_ = const_cast< ::ZPMeta::MetaCmd_Sync*>(&::ZPMeta::MetaCmd_Sync::default_instance());
}

MetaCmd::MetaCmd(const MetaCmd& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void MetaCmd::SharedCtor() {
  _cached_size_ = 0;
  type_ = 1;
  join_ = NULL;
  ping_ = NULL;
  update_ = NULL;
  sync_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MetaCmd::~MetaCmd() {
  SharedDtor();
}

void MetaCmd::SharedDtor() {
  if (this != default_instance_) {
    delete join_;
    delete ping_;
    delete update_;
    delete sync_;
  }
}

void MetaCmd::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MetaCmd::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MetaCmd_descriptor_;
}

const MetaCmd& MetaCmd::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_zp_5fmeta_2eproto();
  return *default_instance_;
}

MetaCmd* MetaCmd::default_instance_ = NULL;

MetaCmd* MetaCmd::New() const {
  return new MetaCmd;
}

void MetaCmd::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    type_ = 1;
    if (has_join()) {
      if (join_ != NULL) join_->::ZPMeta::MetaCmd_Join::Clear();
    }
    if (has_ping()) {
      if (ping_ != NULL) ping_->::ZPMeta::MetaCmd_Ping::Clear();
    }
    if (has_update()) {
      if (update_ != NULL) update_->::ZPMeta::MetaCmd_Update::Clear();
    }
    if (has_sync()) {
      if (sync_ != NULL) sync_->::ZPMeta::MetaCmd_Sync::Clear();
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool MetaCmd::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .ZPMeta.MetaCmd.Type type = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::ZPMeta::MetaCmd_Type_IsValid(value)) {
            set_type(static_cast< ::ZPMeta::MetaCmd_Type >(value));
          } else {
            mutable_unknown_fields()->AddVarint(1, value);
          }
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_join;
        break;
      }

      // optional .ZPMeta.MetaCmd.Join join = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_join:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_join()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_ping;
        break;
      }

      // optional .ZPMeta.MetaCmd.Ping ping = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_ping:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_ping()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(34)) goto parse_update;
        break;
      }

      // optional .ZPMeta.MetaCmd.Update update = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_update:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_update()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(42)) goto parse_sync;
        break;
      }

      // optional .ZPMeta.MetaCmd.Sync sync = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_sync:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_sync()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void MetaCmd::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required .ZPMeta.MetaCmd.Type type = 1;
  if (has_type()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->type(), output);
  }

  // optional .ZPMeta.MetaCmd.Join join = 2;
  if (has_join()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->join(), output);
  }

  // optional .ZPMeta.MetaCmd.Ping ping = 3;
  if (has_ping()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->ping(), output);
  }

  // optional .ZPMeta.MetaCmd.Update update = 4;
  if (has_update()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, this->update(), output);
  }

  // optional .ZPMeta.MetaCmd.Sync sync = 5;
  if (has_sync()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      5, this->sync(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* MetaCmd::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required .ZPMeta.MetaCmd.Type type = 1;
  if (has_type()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->type(), target);
  }

  // optional .ZPMeta.MetaCmd.Join join = 2;
  if (has_join()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->join(), target);
  }

  // optional .ZPMeta.MetaCmd.Ping ping = 3;
  if (has_ping()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        3, this->ping(), target);
  }

  // optional .ZPMeta.MetaCmd.Update update = 4;
  if (has_update()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        4, this->update(), target);
  }

  // optional .ZPMeta.MetaCmd.Sync sync = 5;
  if (has_sync()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        5, this->sync(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int MetaCmd::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required .ZPMeta.MetaCmd.Type type = 1;
    if (has_type()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->type());
    }

    // optional .ZPMeta.MetaCmd.Join join = 2;
    if (has_join()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->join());
    }

    // optional .ZPMeta.MetaCmd.Ping ping = 3;
    if (has_ping()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->ping());
    }

    // optional .ZPMeta.MetaCmd.Update update = 4;
    if (has_update()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->update());
    }

    // optional .ZPMeta.MetaCmd.Sync sync = 5;
    if (has_sync()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->sync());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MetaCmd::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const MetaCmd* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const MetaCmd*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void MetaCmd::MergeFrom(const MetaCmd& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_type()) {
      set_type(from.type());
    }
    if (from.has_join()) {
      mutable_join()->::ZPMeta::MetaCmd_Join::MergeFrom(from.join());
    }
    if (from.has_ping()) {
      mutable_ping()->::ZPMeta::MetaCmd_Ping::MergeFrom(from.ping());
    }
    if (from.has_update()) {
      mutable_update()->::ZPMeta::MetaCmd_Update::MergeFrom(from.update());
    }
    if (from.has_sync()) {
      mutable_sync()->::ZPMeta::MetaCmd_Sync::MergeFrom(from.sync());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void MetaCmd::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MetaCmd::CopyFrom(const MetaCmd& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MetaCmd::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  if (has_join()) {
    if (!this->join().IsInitialized()) return false;
  }
  if (has_ping()) {
    if (!this->ping().IsInitialized()) return false;
  }
  if (has_update()) {
    if (!this->update().IsInitialized()) return false;
  }
  if (has_sync()) {
    if (!this->sync().IsInitialized()) return false;
  }
  return true;
}

void MetaCmd::Swap(MetaCmd* other) {
  if (other != this) {
    std::swap(type_, other->type_);
    std::swap(join_, other->join_);
    std::swap(ping_, other->ping_);
    std::swap(update_, other->update_);
    std::swap(sync_, other->sync_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata MetaCmd::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MetaCmd_descriptor_;
  metadata.reflection = MetaCmd_reflection_;
  return metadata;
}


// ===================================================================

const ::google::protobuf::EnumDescriptor* MetaCmdResponse_Type_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MetaCmdResponse_Type_descriptor_;
}
bool MetaCmdResponse_Type_IsValid(int value) {
  switch(value) {
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

#ifndef _MSC_VER
const MetaCmdResponse_Type MetaCmdResponse::JOIN;
const MetaCmdResponse_Type MetaCmdResponse::PING;
const MetaCmdResponse_Type MetaCmdResponse::UPDATE;
const MetaCmdResponse_Type MetaCmdResponse::SYNC;
const MetaCmdResponse_Type MetaCmdResponse::Type_MIN;
const MetaCmdResponse_Type MetaCmdResponse::Type_MAX;
const int MetaCmdResponse::Type_ARRAYSIZE;
#endif  // _MSC_VER
#ifndef _MSC_VER
const int MetaCmdResponse_Status::kCodeFieldNumber;
const int MetaCmdResponse_Status::kMsgFieldNumber;
#endif  // !_MSC_VER

MetaCmdResponse_Status::MetaCmdResponse_Status()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void MetaCmdResponse_Status::InitAsDefaultInstance() {
}

MetaCmdResponse_Status::MetaCmdResponse_Status(const MetaCmdResponse_Status& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void MetaCmdResponse_Status::SharedCtor() {
  _cached_size_ = 0;
  code_ = 0;
  msg_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MetaCmdResponse_Status::~MetaCmdResponse_Status() {
  SharedDtor();
}

void MetaCmdResponse_Status::SharedDtor() {
  if (msg_ != &::google::protobuf::internal::kEmptyString) {
    delete msg_;
  }
  if (this != default_instance_) {
  }
}

void MetaCmdResponse_Status::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MetaCmdResponse_Status::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MetaCmdResponse_Status_descriptor_;
}

const MetaCmdResponse_Status& MetaCmdResponse_Status::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_zp_5fmeta_2eproto();
  return *default_instance_;
}

MetaCmdResponse_Status* MetaCmdResponse_Status::default_instance_ = NULL;

MetaCmdResponse_Status* MetaCmdResponse_Status::New() const {
  return new MetaCmdResponse_Status;
}

void MetaCmdResponse_Status::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    code_ = 0;
    if (has_msg()) {
      if (msg_ != &::google::protobuf::internal::kEmptyString) {
        msg_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool MetaCmdResponse_Status::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 code = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &code_)));
          set_has_code();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_msg;
        break;
      }

      // optional bytes msg = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_msg:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_msg()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void MetaCmdResponse_Status::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required int32 code = 1;
  if (has_code()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->code(), output);
  }

  // optional bytes msg = 2;
  if (has_msg()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytes(
      2, this->msg(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* MetaCmdResponse_Status::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required int32 code = 1;
  if (has_code()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->code(), target);
  }

  // optional bytes msg = 2;
  if (has_msg()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        2, this->msg(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int MetaCmdResponse_Status::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 code = 1;
    if (has_code()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->code());
    }

    // optional bytes msg = 2;
    if (has_msg()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->msg());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MetaCmdResponse_Status::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const MetaCmdResponse_Status* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const MetaCmdResponse_Status*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void MetaCmdResponse_Status::MergeFrom(const MetaCmdResponse_Status& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_code()) {
      set_code(from.code());
    }
    if (from.has_msg()) {
      set_msg(from.msg());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void MetaCmdResponse_Status::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MetaCmdResponse_Status::CopyFrom(const MetaCmdResponse_Status& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MetaCmdResponse_Status::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void MetaCmdResponse_Status::Swap(MetaCmdResponse_Status* other) {
  if (other != this) {
    std::swap(code_, other->code_);
    std::swap(msg_, other->msg_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata MetaCmdResponse_Status::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MetaCmdResponse_Status_descriptor_;
  metadata.reflection = MetaCmdResponse_Status_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int MetaCmdResponse::kTypeFieldNumber;
const int MetaCmdResponse::kStatusFieldNumber;
#endif  // !_MSC_VER

MetaCmdResponse::MetaCmdResponse()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void MetaCmdResponse::InitAsDefaultInstance() {
  status_ = const_cast< ::ZPMeta::MetaCmdResponse_Status*>(&::ZPMeta::MetaCmdResponse_Status::default_instance());
}

MetaCmdResponse::MetaCmdResponse(const MetaCmdResponse& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void MetaCmdResponse::SharedCtor() {
  _cached_size_ = 0;
  type_ = 1;
  status_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MetaCmdResponse::~MetaCmdResponse() {
  SharedDtor();
}

void MetaCmdResponse::SharedDtor() {
  if (this != default_instance_) {
    delete status_;
  }
}

void MetaCmdResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MetaCmdResponse::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MetaCmdResponse_descriptor_;
}

const MetaCmdResponse& MetaCmdResponse::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_zp_5fmeta_2eproto();
  return *default_instance_;
}

MetaCmdResponse* MetaCmdResponse::default_instance_ = NULL;

MetaCmdResponse* MetaCmdResponse::New() const {
  return new MetaCmdResponse;
}

void MetaCmdResponse::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    type_ = 1;
    if (has_status()) {
      if (status_ != NULL) status_->::ZPMeta::MetaCmdResponse_Status::Clear();
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool MetaCmdResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .ZPMeta.MetaCmdResponse.Type type = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::ZPMeta::MetaCmdResponse_Type_IsValid(value)) {
            set_type(static_cast< ::ZPMeta::MetaCmdResponse_Type >(value));
          } else {
            mutable_unknown_fields()->AddVarint(1, value);
          }
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_status;
        break;
      }

      // required .ZPMeta.MetaCmdResponse.Status status = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_status:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_status()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void MetaCmdResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required .ZPMeta.MetaCmdResponse.Type type = 1;
  if (has_type()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->type(), output);
  }

  // required .ZPMeta.MetaCmdResponse.Status status = 2;
  if (has_status()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->status(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* MetaCmdResponse::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required .ZPMeta.MetaCmdResponse.Type type = 1;
  if (has_type()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->type(), target);
  }

  // required .ZPMeta.MetaCmdResponse.Status status = 2;
  if (has_status()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->status(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int MetaCmdResponse::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required .ZPMeta.MetaCmdResponse.Type type = 1;
    if (has_type()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->type());
    }

    // required .ZPMeta.MetaCmdResponse.Status status = 2;
    if (has_status()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->status());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MetaCmdResponse::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const MetaCmdResponse* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const MetaCmdResponse*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void MetaCmdResponse::MergeFrom(const MetaCmdResponse& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_type()) {
      set_type(from.type());
    }
    if (from.has_status()) {
      mutable_status()->::ZPMeta::MetaCmdResponse_Status::MergeFrom(from.status());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void MetaCmdResponse::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MetaCmdResponse::CopyFrom(const MetaCmdResponse& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MetaCmdResponse::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  if (has_status()) {
    if (!this->status().IsInitialized()) return false;
  }
  return true;
}

void MetaCmdResponse::Swap(MetaCmdResponse* other) {
  if (other != this) {
    std::swap(type_, other->type_);
    std::swap(status_, other->status_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata MetaCmdResponse::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MetaCmdResponse_descriptor_;
  metadata.reflection = MetaCmdResponse_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace ZPMeta

// @@protoc_insertion_point(global_scope)
